# Generated by Django 5.2.1 on 2025-05-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"ordering": ("-id",)},
        ),
    ]
