# Generated by Django 5.2.1 on 2025-05-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={"ordering": ("-id",), "verbose_name": "Ad"},
        ),
    ]
