# Generated by Django 5.2.1 on 2025-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='exchange',
            constraint=models.UniqueConstraint(fields=('ad_sender', 'ad_receiver'), name='unique_exchange_pair'),
        ),
    ]
